package resource

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// LockfileEntry represents a locked dependency
type LockfileEntry struct {
	// For git dependencies
	Git       string `yaml:"git,omitempty"`
	Ref       string `yaml:"ref,omitempty"`
	Commit    string `yaml:"commit,omitempty"`
	FetchedAt string `yaml:"fetched_at,omitempty"`

	// For URL dependencies
	URL      string `yaml:"url,omitempty"`
	Checksum string `yaml:"checksum,omitempty"`
}

// Lockfile represents the dependencies.lock file
type Lockfile struct {
	Version        int                      `yaml:"version"`
	Generated      string                   `yaml:"generated"`
	Platform       string                   `yaml:"platform"`
	Dependencies   map[string]LockfileEntry `yaml:"dependencies"`
	SystemWarnings []string                 `yaml:"system_warnings,omitempty"`
}

// LockfileManager manages lockfile generation and validation
type LockfileManager struct {
	lockfilePath string
	platform     string
	architecture string
}

// NewLockfileManager creates a new LockfileManager
func NewLockfileManager(workspaceRoot, platform, architecture string) *LockfileManager {
	return &LockfileManager{
		lockfilePath: filepath.Join(workspaceRoot, "buildy", "dependencies.lock"),
		platform:     platform,
		architecture: architecture,
	}
}

// Exists checks if a lockfile exists
func (lm *LockfileManager) Exists() bool {
	_, err := os.Stat(lm.lockfilePath)
	return err == nil
}

// Load loads an existing lockfile
func (lm *LockfileManager) Load() (*Lockfile, error) {
	data, err := os.ReadFile(lm.lockfilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read lockfile: %w", err)
	}

	var lockfile Lockfile
	if err := yaml.Unmarshal(data, &lockfile); err != nil {
		return nil, fmt.Errorf("failed to parse lockfile: %w", err)
	}

	return &lockfile, nil
}

// Generate generates a new lockfile from resolved dependencies
func (lm *LockfileManager) Generate(deps map[string]*Dependency, fetchManager *FetchManager, warnings []string) (*Lockfile, error) {
	lockfile := &Lockfile{
		Version:        1,
		Generated:      time.Now().UTC().Format(time.RFC3339),
		Platform:       fmt.Sprintf("%s-%s", lm.platform, lm.architecture),
		Dependencies:   make(map[string]LockfileEntry),
		SystemWarnings: warnings,
	}

	for name, dep := range deps {
		if dep.Type == DepTypeFetch {
			entry := LockfileEntry{
				FetchedAt: time.Now().UTC().Format(time.RFC3339),
			}

			// Get git commit if it's a git repo
			if dep.Path != "" {
				gitDir := filepath.Join(dep.Path, ".git")
				if _, err := os.Stat(gitDir); err == nil {
					// It's a git repo
					commit, err := fetchManager.GetGitCommit(dep.Path)
					if err == nil {
						entry.Commit = commit
					}
				}
			}

			lockfile.Dependencies[name] = entry
		}
	}

	return lockfile, nil
}

// Save saves the lockfile to disk
func (lm *LockfileManager) Save(lockfile *Lockfile) error {
	// Ensure directory exists
	dir := filepath.Dir(lm.lockfilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create lockfile directory: %w", err)
	}

	data, err := yaml.Marshal(lockfile)
	if err != nil {
		return fmt.Errorf("failed to marshal lockfile: %w", err)
	}

	// Add header comment
	header := "# Buildy dependencies lockfile - DO NOT EDIT\n# Generated by buildy --update-lock\n# This file ensures reproducible builds by pinning exact dependency versions\n\n"
	content := header + string(data)

	if err := os.WriteFile(lm.lockfilePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write lockfile: %w", err)
	}

	log.Printf("Generated lockfile: %s", lm.lockfilePath)
	return nil
}

// Validate validates that current dependencies match the lockfile
func (lm *LockfileManager) Validate(deps map[string]*Dependency, fetchManager *FetchManager) error {
	lockfile, err := lm.Load()
	if err != nil {
		return err
	}

	for name, lockedEntry := range lockfile.Dependencies {
		dep, ok := deps[name]
		if !ok {
			log.Printf("WARNING: Locked dependency '%s' not found in current config", name)
			continue
		}

		if dep.Type == DepTypeFetch && dep.Path != "" && lockedEntry.Commit != "" {
			// Verify git commit matches
			currentCommit, err := fetchManager.GetGitCommit(dep.Path)
			if err != nil {
				return fmt.Errorf("failed to get commit for %s: %w", name, err)
			}

			if currentCommit != lockedEntry.Commit {
				return fmt.Errorf(
					"dependency '%s' commit mismatch:\n  locked:  %s\n  current: %s\n\nRun 'buildy --update-lock' to update the lockfile",
					name, lockedEntry.Commit, currentCommit,
				)
			}
		}
	}

	log.Printf("Lockfile validation passed")
	return nil
}

// Update updates the lockfile with current dependency state
func (lm *LockfileManager) Update(deps map[string]*Dependency, fetchManager *FetchManager, warnings []string) error {
	lockfile, err := lm.Generate(deps, fetchManager, warnings)
	if err != nil {
		return err
	}
	return lm.Save(lockfile)
}

// GetPath returns the lockfile path
func (lm *LockfileManager) GetPath() string {
	return lm.lockfilePath
}
